# Generated by Django 6.0 on 2025-12-11 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogpost', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
